# Generated by Django 3.0.4 on 2020-05-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTPayloadTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('iat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'JWT Payload Tracks',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='pupil',
            name='Roll',
            field=models.IntegerField(),
        ),
    ]
